apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: k8s-monitoring
      targetRevision: 1.6.38
      helm:
        valueFiles:
          - $values/gitops/monitoring/alloy/values.yaml
    - repoURL: https://github.com/throdriguesdev/demo-dodfsa.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/throdriguesdev/demo-dodfsa.git
      targetRevision: HEAD
      path: gitops/monitoring/alloy
      directory:
        recurse: false
        include: "ingress.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
