apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/throdriguesdev/demo-dodfsa.git
    targetRevision: HEAD
    path: gitops/monitoring/alloy
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
