apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 8.8.2
      helm:
        valueFiles:
          - $values/gitops/monitoring/grafana/values.yaml
    - repoURL: https://github.com/throdriguesdev/demo-dodfsa.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/throdriguesdev/demo-dodfsa.git
      targetRevision: HEAD
      path: gitops/monitoring/grafana
      directory:
        recurse: false
        include: "external-secret.yaml"
    - repoURL: https://github.com/throdriguesdev/demo-dodfsa.git
      targetRevision: HEAD
      path: gitops/monitoring/grafana/dashboards
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /metadata/annotations/refreshTime
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
