cluster:
  name: devopsdays-dev

externalServices:
  prometheus:
    host: http://mimir.monitoring.svc.cluster.local:8080
    writeEndpoint: /api/v1/push
  loki:
    host: http://loki.monitoring.svc.cluster.local:3100
    writeEndpoint: /loki/api/v1/push
  tempo:
    host: tempo.monitoring.svc.cluster.local
    port: 4317

clusterMetrics:
  enabled: true

clusterEvents:
  enabled: true

podLogs:
  enabled: true

alloy-metrics:
  enabled: true
  alloy:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
    extraPorts:
      - name: http-ui
        port: 12345
        targetPort: 12345
        protocol: TCP

alloy-logs:
  enabled: true
  alloy:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi
