apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env
  namespace: demo-app
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy.monitoring.svc.cluster.local:4317"
  OTEL_RESOURCE_ATTRIBUTES: "service.namespace=demo-app,deployment.environment=dev"
  SERVICE_VERSION: "1.0.0"
  DATABASE_URL: "postgresql://app:app@postgres.demo-app.svc.cluster.local:5432/appdb"
  REDIS_URL: "redis://redis.demo-app.svc.cluster.local:6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.demo-app.svc.cluster.local:5672/"
  API_URL: "http://api.demo-app.svc.cluster.local:8080"
  FRAUD_URL: "http://fraud.demo-app.svc.cluster.local:9094"
  INVENTORY_URL: "http://inventory.demo-app.svc.cluster.local:9093"
  PAYMENT_URL: "http://payment-gateway.demo-app.svc.cluster.local:9092"
  NOTIFICATION_URL: "http://notification.demo-app.svc.cluster.local:9091"
